import pytest
from day7.day7 import day7_part1_algorithm, day7_part2_algorithm


def test_day7_part1_full():
    test_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".replace("\r", "")
    expected_output = 21
    assert day7_part1_algorithm(test_input) == expected_output


def test_day7_part2_full():
    test_input = test_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".replace("\r", "")
    expected_output = 40
    assert day7_part2_algorithm(test_input) == expected_output
